### ISSUE TITLE
Python Compatibility - please help

### ISSUE THREAD

**Issue by taharslan44** [exploitagency/github-rfpwnon#12]
I get it, this script no longer works because of python3 and its written for python2. 

But there MUST be a way of running it. Please python gods, help me, how can i run this script?

I have latest kali in bare metal and a yard stick one. If you recommend another de Brujin brute-forcer, I'm open to suggestions. Just lead me. Thank you in advance.

**Comment by exploitagency** [comment]
I did not do a lot of testing but I made this for you today because of the kind email you sent me.  This was able to trigger my usual RF controlled appliance that I use for testing on and off although my yardstick one kept disconnecting from the usb passthrough on my virtual machine, I also updated the firmware today on my yardstick ones so unsure which is the culprit.  I would need to do a lot of testing on different devices before officially releasing a python3 port but I figure I will leave this here for anyone else that may be interested.

[rfpwnon-python3.zip](https://github.com/exploitagency/github-rfpwnon/files/8748830/rfpwnon-python3.zip)
